
type SpatialThing {

  canonicalUrl: String
  displayUsername: String
  inScopeOf: [AccountingScope!]

}

type SpatialThingsPage{
  page_info: PageInfo
  edges: [SpatialThing]
  totalCount: Int
}

type Query {
    spatialThingsPages(limit: Int, before: [Cursor], after: [Cursor]): [SpatialThingsPage!]
}