""" Only used for workaround mentioned in readme """
scalar ExternalType

""" REMOVEME! only included here to help with merging, but should be removed from the final schema as this is already defined in CommonsPub"""
type PageInfo {
    workaround: String
}
""" REMOVEME! only included here to help with merging, but should be removed from the final schema as this is already defined in CommonsPub"""
type Cursor {
    workaround: String
}